# Generated by Django 5.0.1 on 2026-04-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calculation_type',
            field=models.CharField(choices=[('sqft', 'Square Feet'), ('rm', 'Running Meter'), ('rf', 'Running Feet'), ('nos', 'Number')], default='nos', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
