# Generated by Django 5.0.1 on 2026-04-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0002_item_calculation_type_item_description_item_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='item_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='material_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='running_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
