# Generated by Django 5.0.1 on 2026-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0003_remove_item_rate_item_count_item_depth_item_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
        migrations.RemoveField(
            model_name='item',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
        migrations.RemoveField(
            model_name='item',
            name='material_rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='running_value',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
