# Generated by Django 5.0.1 on 2026-04-29 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0004_remove_item_count_remove_item_depth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('quotation_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('project_type', models.CharField(max_length=50)),
                ('length', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('running_value', models.FloatField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('total_amount', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quotation.item')),
                ('sub_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quotation.subunit')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quotation.unit')),
            ],
        ),
    ]
