# Generated by Django 5.0.1 on 2026-04-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0005_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotation',
        ),
    ]
