# Generated by Django 5.0.1 on 2026-05-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0006_delete_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('quotation_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('project_type', models.CharField(max_length=200)),
            ],
        ),
    ]
