# Generated by Django 5.0.1 on 2026-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0008_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='item_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
