# Generated by Django 5.0.1 on 2026-05-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0009_quotationitem_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='d_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='h_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='l_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='qty_val',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
