# Generated by Django 5.0.1 on 2026-05-14 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0010_quotationitem_d_val_quotationitem_h_val_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Quotation.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Quotation.quotationgroup'),
        ),
    ]
