# Generated by Django 5.0.1 on 2026-05-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0011_quotationgroup_quotationitem_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='group',
        ),
        migrations.DeleteModel(
            name='QuotationGroup',
        ),
    ]
