# Generated by Django 5.0.1 on 2026-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0013_client_remove_quotation_client_name_quotation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='client',
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
