# Generated by Django 5.0.1 on 2026-05-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0017_customer_remove_quotation_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='discount_rate',
            new_name='discount_percentage',
        ),
    ]
