# Generated by Django 5.0.1 on 2026-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0018_rename_discount_rate_quotationitem_discount_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', max_length=15),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
