# Generated by Django 5.0.1 on 2026-05-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0019_remove_quotationitem_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subunit',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', max_length=15),
        ),
        migrations.AddField(
            model_name='subunit',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
