# Generated by Django 5.0.1 on 2026-05-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0020_subunit_discount_type_subunit_discount_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subunit',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='subunit',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='unit',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage (%)'), ('flat', 'Flat Amount (₹)')], default='percentage', max_length=15),
        ),
        migrations.AddField(
            model_name='unit',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
