# Generated by Django 5.0.1 on 2026-05-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0021_remove_subunit_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
