# Generated by Django 6.0.5 on 2026-06-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0023_material_sub_unit_alter_material_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='sub_unit',
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
