# Generated by Django 6.0.5 on 2026-06-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0024_remove_material_sub_unit_alter_material_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='sub_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quotation.subunit'),
        ),
    ]
