# Generated by Django 6.0.5 on 2026-06-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0026_template_templateitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='material',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.DeleteModel(
            name='TemplateItem',
        ),
    ]
