# Generated by Django 6.0.5 on 2026-06-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0028_template_templateitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
