# Generated by Django 6.0.5 on 2026-06-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0029_alter_quotation_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quotation_item_images/'),
        ),
    ]
